---
- name: NGINX | Install epel release , Git
  become: true
  ansible.builtin.yum:
    name: 
      - epel-release
      - git
    state: present
- name: Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start-nginx
- name: Create general config
  become: true
  ansible.legacy.template:
    src: "{{ src_light }}"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"
  notify: reload-nginx
- name: Lighthouse | Creates directory
  become: true
  ansible.builtin.file:
    path: "{{ lighthouse_location_dir }}"
    state: directory
    mode: "0644"
- name: Lighthouse | Copy from Git
  become: true
  ansible.legacy.git:
    repo: "{{ lighthouse_vcs }}"
    version: "v11.5.0"
    dest: "{{ lighthouse_location_dir }}"
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.legacy.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: reload-nginx
